
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Fri Oct 10 20:38:04 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 30;
  static final int SIGNED = 31;
  static final int TIMES = 48;
  static final int GT = 56;
  static final int ARROW = 79;
  static final int DIVASSIGN = 69;
  static final int CONST = 33;
  static final int GE = 57;
  static final int PERIOD = 78;
  static final int REGISTER = 28;
  static final int ENUM = 23;
  static final int RBRACK = 11;
  static final int SIZEOF = 35;
  static final int COMMA = 14;
  static final int RBRACE = 13;
  static final int RPAREN = 9;
  static final int LBRACK = 10;
  static final int LT = 54;
  static final int INCREMENT = 76;
  static final int SUBASSIGN = 67;
  static final int DOUBLE = 32;
  static final int BWISEANDASSIGN = 71;
  static final int STRUCT = 34;
  static final int LBRACE = 12;
  static final int LPAREN = 8;
  static final int MODASSIGN = 70;
  static final int TILDE = 63;
  static final int LE = 55;
  static final int VAR = 82;
  static final int FLOAT = 37;
  static final int BITWISEAND = 60;
  static final int GOTO = 26;
  static final int EQ = 52;
  static final int LSHIFTASSIGN = 74;
  static final int MODULUS = 50;
  static final int LONG = 36;
  static final int PLUS = 46;
  static final int DIVIDE = 49;
  static final int WHILE = 44;
  static final int UNION = 38;
  static final int ASSIGN = 51;
  static final int CHAR = 45;
  static final int ADDASSIGN = 66;
  static final int DO = 21;
  static final int FOR = 25;
  static final int VOID = 39;
  static final int EXTERN = 24;
  static final int RETURN = 29;
  static final int ELSE = 22;
  static final int FUN = 81;
  static final int BREAK = 17;
  static final int INT = 6;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 7;
  static final int ELIPSES = 80;
  static final int DEFAULT = 20;
  static final int MULASSIGN = 68;
  static final int DECREMENT = 77;
  static final int MINUS = 47;
  static final int OR = 59;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 5;
  static final int CONTINUE = 19;
  static final int IF = 27;
  static final int UNSIGNED = 41;
  static final int BWISEOR = 61;
  static final int ID = 2;
  static final int COLON = 15;
  static final int BWISEXOR = 62;
  static final int BWISEORASSIGN = 72;
  static final int RSHIFTASSIGN = 75;
  static final int VOLATILE = 40;
  static final int CHAR_LITERAL = 4;
  static final int CASE = 18;
  static final int BWISEXORASSIGN = 73;
  static final int RSHIFT = 65;
  static final int NEQ = 53;
  static final int AND = 58;
  static final int STATIC = 42;
  static final int LSHIFT = 64;
  static final int TYPEDEF = 43;
  static final int AUTO = 16;

  /* non terminals */
  static final int primary_expression = 3;
  static final int assignment_expression = 18;
  static final int Var = 2;
  static final int cast_expression = 6;
  static final int AND_expression = 12;
  static final int unary_expression = 5;
  static final int conditional_expression = 17;
  static final int $START = 0;
  static final int shift_expression = 9;
  static final int postfix_expression = 4;
  static final int exclusive_OR_expression = 13;
  static final int logical_AND_expression = 15;
  static final int expression = 19;
  static final int inclusive_OR_expression = 14;
  static final int additive_expression = 8;
  static final int relational_expression = 10;
  static final int equality_expression = 11;
  static final int Exp = 1;
  static final int logical_OR_expression = 16;
  static final int argument_expression_list = 21;
  static final int constant_expression = 20;
  static final int multiplicative_expression = 7;
  static final int unary_operator = 22;
  static final int type_name = 23;
}

