

//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Jan 18 14:18:26 CST 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 51;
  static final int SIGNED = 46;
  static final int TIMES = 19;
  static final int GT = 25;
  static final int ARROW = 68;
  static final int DIVASSIGN = 67;
  static final int CONST = 53;
  static final int GE = 26;
  static final int PERIOD = 79;
  static final int REGISTER = 40;
  static final int ENUM = 57;
  static final int RBRACK = 14;
  static final int SIZEOF = 45;
  static final int COMMA = 8;
  static final int RBRACE = 16;
  static final int RPAREN = 12;
  static final int LBRACK = 13;
  static final int LT = 23;
  static final int INCREMENT = 72;
  static final int SUBASSIGN = 69;
  static final int DOUBLE = 49;
  static final int BWISEANDASSIGN = 74;
  static final int STRUCT = 43;
  static final int LBRACE = 15;
  static final int LPAREN = 11;
  static final int MODASSIGN = 75;
  static final int TILDE = 76;
  static final int LE = 24;
  static final int VAR = 37;
  static final int BITWISEAND = 80;
  static final int FLOAT = 52;
  static final int GOTO = 56;
  static final int EQ = 21;
  static final int LSHIFTASSIGN = 61;
  static final int MODULUS = 81;
  static final int LONG = 55;
  static final int PLUS = 17;
  static final int DIVIDE = 20;
  static final int WHILE = 32;
  static final int UNION = 50;
  static final int ASSIGN = 29;
  static final int CHAR = 58;
  static final int ADDASSIGN = 71;
  static final int DO = 34;
  static final int FOR = 33;
  static final int VOID = 54;
  static final int EXTERN = 48;
  static final int RETURN = 47;
  static final int ELSE = 31;
  static final int BREAK = 35;
  static final int FUN = 36;
  static final int INT = 7;
  static final int STRING_LITERAL = 3;
  static final int EOF = 0;
  static final int SEMICOLON = 10;
  static final int MULASSIGN = 73;
  static final int ELIPSES = 62;
  static final int DECREMENT = 70;
  static final int MINUS = 18;
  static final int OR = 28;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 5;
  static final int CONTINUE = 41;
  static final int IF = 30;
  static final int UNSIGNED = 39;
  static final int BWISEOR = 77;
  static final int ID = 2;
  static final int COLON = 9;
  static final int BWISEXOR = 78;
  static final int BWISEORASSIGN = 63;
  static final int RSHIFTASSIGN = 60;
  static final int VOLATILE = 38;
  static final int CHAR_LITERAL = 6;
  static final int RSHIFT = 65;
  static final int BWISEXORASSIGN = 64;
  static final int NEQ = 22;
  static final int AND = 27;
  static final int STATIC = 44;
  static final int LSHIFT = 66;
  static final int TYPEDEF = 42;
  static final int AUTO = 59;
}
